# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-1  # Change to reflect your region

permissions:
  id-token: write    # Required for requesting the OIDC JWT
  contents: read     # Required for actions/checkout

jobs:
  AssumeRoleAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::542741497010:role/GitHubAction-AssumeRoleWithAction # Update with your IAM role ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: WhoAmI (verify role assumption)
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5  # Use your preferred version

      - name: Terraform Init
        run: terraform init
        working-directory: /terrafrom  # Change to your Terraform directory if needed

      - name: Terraform Validate
        run: terraform validate
        working-directory: /terrafrom

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: /terrafrom

      - name: Terraform Apply (main branch only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: /terrafrom
